//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaNiesprawnosci {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    public sealed partial class MainSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MainSettings defaultInstance = ((MainSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainSettings())));
        
        public static MainSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Incydent</string>\r\n  <string>Bez następstw</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TEffectFlightSafety {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TEffectFlightSafety"]));
            }
            set {
                this["TEffectFlightSafety"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Przerwanie startu</string>
  <string>Przerwanie wykonywania zadania w powietrzu</string>
  <string>Praca na ziemii</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TEffectCompletingTask {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TEffectCompletingTask"]));
            }
            set {
                this["TEffectCompletingTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Wymiana częsci (agregatu)</string>
  <string>Naprawa częsci (agregatu)</string>
  <string>Resuscytacja</string>
  <string>Oczyszczenie złącza (filtra)</string>
  <string>Inne</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TSolutionProcedure {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TSolutionProcedure"]));
            }
            set {
                this["TSolutionProcedure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Badania</string>
  <string>Remont</string>
  <string>Naprawa</string>
  <string>Kasacja</string>
  <string>Inne</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TItemProcedure {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TItemProcedure"]));
            }
            set {
                this["TItemProcedure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>011</string>
  <string>012</string>
  <string>013</string>
  <string>014</string>
  <string>015</string>
  <string>016</string>
  <string>017</string>
  <string>018</string>
  <string>020</string>
  <string>021</string>
  <string>022</string>
  <string>023</string>
  <string>024</string>
  <string>025</string>
  <string>026</string>
  <string>027</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TAircraft {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TAircraft"]));
            }
            set {
                this["TAircraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Obsługa przedlotowa</string>
  <string>Obsługa polotowa</string>
  <string>Obsługa okresowa</string>
  <string>Podczas lotu</string>
  <string>Podczas kołowania</string>
  <string>Po uruchomieniu silników</string>
  <string>Podczas próby silników</string>
  <string>Servicing</string>
  <string>Dni techniki</string>
  <string>Obsługa roczna</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TCircumstances {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TCircumstances"]));
            }
            set {
                this["TCircumstances"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>It</string>\r\n  <string>Tz</string>\r\n  <string>X</string>\r\n</ArrayOfString>" +
            "")]
        public global::System.Collections.Specialized.StringCollection TClassification {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TClassification"]));
            }
            set {
                this["TClassification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Awionika</string>
  <string>Płatowiec i Silnik</string>
  <string>Urządzenia specjalne i walka elektroniczna</string>
  <string>Urządzenia radioelektroniczne</string>
  <string>Osprzęt</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TSpeciality {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TSpeciality"]));
            }
            set {
                this["TSpeciality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>CASA C-295 M</string>\r\n  <string>M28 GC</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TAircraftType {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TAircraftType"]));
            }
            set {
                this["TAircraftType"] = value;
            }
        }
    }
}
