//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BazaNiesprawnosci.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BazaNiesprawnosci.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Nie udało się zmienić parametrów bazy danych..
        /// </summary>
        internal static string AcInfoError {
            get {
                return ResourceManager.GetString("AcInfoError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zanim doda się statek powietrzny do bazy danych należy uzupełnic wszystkie pola jego opisu..
        /// </summary>
        internal static string AircraftNotCompleted {
            get {
                return ResourceManager.GetString("AircraftNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Przed dodaniem niesprawności do bazy sprecyzuj samolot na którym wystąpiła niesprawność..
        /// </summary>
        internal static string AircraftWarning {
            get {
                return ResourceManager.GetString("AircraftWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Przed dodaniem niesprawności do bazy ustaw kategorie ATA do której zaliczona jest niesprawność..
        /// </summary>
        internal static string AtaWarning {
            get {
                return ResourceManager.GetString("AtaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ostrzeżenie o zmianach w bazie danych..
        /// </summary>
        internal static string CAircraftRemoveCaption {
            get {
                return ResourceManager.GetString("CAircraftRemoveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy napewno chcesz usunąć dane informacje o statku powietrznym z bazy danych? Nacisnij tak, jeżeli chcesz usunąc zarowno dany wpis z bazy danych jak i wyników wyszukiwania. Naciśnij &quot;Nie&quot; jeżeli chcesz usunąc dany wpis z wyników wyszukiwania. Naciśnij anuluj w celu zaniechania czynności.
        /// </summary>
        internal static string CAircraftRemoveFromDatabase {
            get {
                return ResourceManager.GetString("CAircraftRemoveFromDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak danych wyszukiwania. Wczytuje wszystkie statki z bazy danych..
        /// </summary>
        internal static string CAircraftSearchNoDataLoadAll {
            get {
                return ResourceManager.GetString("CAircraftSearchNoDataLoadAll", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przed dodaniem kategorii do bazy danych należy uzupełnic wszystkie pola jej opisu..
        /// </summary>
        internal static string CategoryNotCompleted {
            get {
                return ResourceManager.GetString("CategoryNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyślne utworzono oraz połączono z nową bazą danych..
        /// </summary>
        internal static string DataBaseCreateOk {
            get {
                return ResourceManager.GetString("DataBaseCreateOk", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Nie można nadpisać bazy danych.
        /// </summary>
        internal static string DataBaseCreateOverwrite {
            get {
                return ResourceManager.GetString("DataBaseCreateOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Poprawiono wybrany wpis w bazie danych..
        /// </summary>
        internal static string DataBaseFixEntryOk {
            get {
                return ResourceManager.GetString("DataBaseFixEntryOk", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Nie udało się wczytać wybranej bazy danych/ nie wybrano bazy danych..
        /// </summary>
        internal static string DataBaseInitializeError {
            get {
                return ResourceManager.GetString("DataBaseInitializeError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyślnie połączono z bazą danych..
        /// </summary>
        internal static string DatabaseInitializeOk {
            get {
                return ResourceManager.GetString("DatabaseInitializeOk", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnych niesprawności o danych parametrach..
        /// </summary>
        internal static string DataBaseNoResults {
            get {
                return ResourceManager.GetString("DataBaseNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Żeby zapisać bazę danych trzeba dodać jakieś niesprawności..
        /// </summary>
        internal static string DataBaseSaveError {
            get {
                return ResourceManager.GetString("DataBaseSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyślnie zapisano bazę danych..
        /// </summary>
        internal static string DatabaseSaveOk {
            get {
                return ResourceManager.GetString("DatabaseSaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Przed dodaniem niesprawności do bazy ustaw datę wystąpienia niesprawności..
        /// </summary>
        internal static string DateAddWarning {
            get {
                return ResourceManager.GetString("DateAddWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usunięto wpis z bazy danych. Dane z wpisu zostały przeniesione do okna dodawania..
        /// </summary>
        internal static string DateBaseChangeEntry {
            get {
                return ResourceManager.GetString("DateBaseChangeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Nie udało się utworzyć bazy danych,.
        /// </summary>
        internal static string DateBaseCreateError {
            get {
                return ResourceManager.GetString("DateBaseCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Wprowadzono niepoprawne hasło..
        /// </summary>
        internal static string DateBasePasswordError {
            get {
                return ResourceManager.GetString("DateBasePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Data usprawnienia nie może być wyższa niż data wystąpienia niesprawności.
        /// </summary>
        internal static string DateEndHigher {
            get {
                return ResourceManager.GetString("DateEndHigher", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Data końca wyszukiwania nie może być mniejsza niż data początkowa wyszukiwania..
        /// </summary>
        internal static string DateToHigher {
            get {
                return ResourceManager.GetString("DateToHigher", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wprowadzono zmiany do niesprawności o id: .
        /// </summary>
        internal static string DefectSuccChanged {
            get {
                return ResourceManager.GetString("DefectSuccChanged", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak wpisów w schowku..
        /// </summary>
        internal static string EmptyClipboard {
            get {
                return ResourceManager.GetString("EmptyClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wyłączono tryb poprawy wpisy bazy danych..
        /// </summary>
        internal static string FixModeDisabled {
            get {
                return ResourceManager.GetString("FixModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uruchomiono tryb poprawy wpisu bazy danych..
        /// </summary>
        internal static string FixModeEnabled {
            get {
                return ResourceManager.GetString("FixModeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Przed dodaniem opisu agregatu wypełnij pola nazwy i pn..
        /// </summary>
        internal static string ItemDescAddWarning {
            get {
                return ResourceManager.GetString("ItemDescAddWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można dodać do bazy danych agregatu bez nazwy..
        /// </summary>
        internal static string ItemDescNoName {
            get {
                return ResourceManager.GetString("ItemDescNoName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usunięto opis agregatu z bazy danych.
        /// </summary>
        internal static string ItemDescRemoveOk {
            get {
                return ResourceManager.GetString("ItemDescRemoveOk", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Wpisz p/n agregatu który chcesz usunąć.
        /// </summary>
        internal static string ItemDescRemoveWarning {
            get {
                return ResourceManager.GetString("ItemDescRemoveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Wprowadź dane wyszukiwania..
        /// </summary>
        internal static string ItemDescSearchWarning {
            get {
                return ResourceManager.GetString("ItemDescSearchWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Przed dodaniem wpisy uzupełnij wszystkie pola.
        /// </summary>
        internal static string NoDataToWrite {
            get {
                return ResourceManager.GetString("NoDataToWrite", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Nie znaleziono w bazie danych agregatu o podanym P/N..
        /// </summary>
        internal static string NotFoundItemDesc {
            get {
                return ResourceManager.GetString("NotFoundItemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono w bazie danych agregatu o podanym P/N. Agregat dodano do bazy danych..
        /// </summary>
        internal static string NotFoundItemDescInsert {
            get {
                return ResourceManager.GetString("NotFoundItemDescInsert", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Nie znaleziono pracowanika..
        /// </summary>
        internal static string NotFoundWorker {
            get {
                return ResourceManager.GetString("NotFoundWorker", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Wprowadzono niepoprawne hasło.
        /// </summary>
        internal static string PasswordBoxBadPassword {
            get {
                return ResourceManager.GetString("PasswordBoxBadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnych danych dot. nowo zamontowanych agregatów.
        /// </summary>
        internal static string SearchAllFoundItemNew {
            get {
                return ResourceManager.GetString("SearchAllFoundItemNew", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znalezino żadnych danych dot. statków powietrznych.
        /// </summary>
        internal static string SearchAllNotFoundAircraft {
            get {
                return ResourceManager.GetString("SearchAllNotFoundAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnych danych dot. kategorii..
        /// </summary>
        internal static string SearchAllNotFoundCategory {
            get {
                return ResourceManager.GetString("SearchAllNotFoundCategory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnych danych dot. niesprawności.
        /// </summary>
        internal static string SearchAllNotFoundDefect {
            get {
                return ResourceManager.GetString("SearchAllNotFoundDefect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnych danych dot. uszkodzonych agregatów..
        /// </summary>
        internal static string SearchAllNotFoundItemDefect {
            get {
                return ResourceManager.GetString("SearchAllNotFoundItemDefect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnych danych dot. agregatów.
        /// </summary>
        internal static string SearchAllNotFoundItemDesc {
            get {
                return ResourceManager.GetString("SearchAllNotFoundItemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnch danych dot. specjalistów..
        /// </summary>
        internal static string SearchAllNotFoundWorker {
            get {
                return ResourceManager.GetString("SearchAllNotFoundWorker", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znalezion żadnych statków powietrznych o zadanych kryteriach..
        /// </summary>
        internal static string SearchNotFoundAircraft {
            get {
                return ResourceManager.GetString("SearchNotFoundAircraft", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnych kategorii o zadanych kryteriach..
        /// </summary>
        internal static string SearchNotFoundCategory {
            get {
                return ResourceManager.GetString("SearchNotFoundCategory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnych niesprawności o zadanych kryteriach..
        /// </summary>
        internal static string SearchNotFoundDefect {
            get {
                return ResourceManager.GetString("SearchNotFoundDefect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string SearchNotFoundItem {
            get {
                return ResourceManager.GetString("SearchNotFoundItem", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnych danych dot. agregatów o zadanych kryteriach..
        /// </summary>
        internal static string SearchNotFoundItemDefect {
            get {
                return ResourceManager.GetString("SearchNotFoundItemDefect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono agreagtów o zadanych kryteriach..
        /// </summary>
        internal static string SearchNotFoundItemDesc {
            get {
                return ResourceManager.GetString("SearchNotFoundItemDesc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnych danych dot. nowo zamontowanych agregatów o zadanych kryteriach..
        /// </summary>
        internal static string SearchNotFoundItemNew {
            get {
                return ResourceManager.GetString("SearchNotFoundItemNew", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie znaleziono żadnych pracowników o zadanych kryteriach..
        /// </summary>
        internal static string SearchNotFoundWorker {
            get {
                return ResourceManager.GetString("SearchNotFoundWorker", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tu wpisz sposób rozwiązania niesprawności.
        /// </summary>
        internal static string SearchSolutionStd {
            get {
                return ResourceManager.GetString("SearchSolutionStd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tu wpisz objawy niesprawności.
        /// </summary>
        internal static string SearchSymptomsStd {
            get {
                return ResourceManager.GetString("SearchSymptomsStd", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Przed dodaniem niesprawności do bazy określ sposób rozwiązania niesprawności..
        /// </summary>
        internal static string SolutionWarning {
            get {
                return ResourceManager.GetString("SolutionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Przed dodaniem niesprawności do bazy określ objawy niesprawności..
        /// </summary>
        internal static string SymptomsWarning {
            get {
                return ResourceManager.GetString("SymptomsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Wprowadź imie, nazwisko przed dodaniem specjalisty..
        /// </summary>
        internal static string WorkerAddWarning {
            get {
                return ResourceManager.GetString("WorkerAddWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie można dodać do bazy danych pracownika bez nazwiska..
        /// </summary>
        internal static string WorkerNoName {
            get {
                return ResourceManager.GetString("WorkerNoName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Błąd. Wprowadź dane wyszukiwania..
        /// </summary>
        internal static string WorkerSearchWarning {
            get {
                return ResourceManager.GetString("WorkerSearchWarning", resourceCulture);
            }
        }
    }
}
